### ISSUE TITLE
Heroku 上でツイート新規登録および一覧ができない

### ISSUE THREAD

**Issue by aximov** [aximov/witness-me#14]
個々のツイート詳細は見れたが、新規登録と一覧ができなくなっている。

localhost では一覧も新規登録もできている。

最近のコミットでツイートのデータモデルをどこかいじったか…？

**Comment by aximov** [comment]
`heroku rollback v7` したが依然として新規登録、一覧画面はみられない。

**Comment by aximov** [comment]
一覧画面が表示できないのは、DBにツイートが1件もない場合を想定していないコードになっているからではないか。

**Comment by 7ma7X** [comment]
ご無沙汰してます。

実は先ほど `https://twitter.com/test` みたいなURLを登録しようとして、そこでサーバーを落としてしまいました。多分DBに変なレコードが入ってしまっていると思います....
悪意があったわけではなく、純粋にツイート以外のURLをどう弾いているのか気になって調べていたのですが、結果的に迷惑をかけてしまいすみませんでした...

**Comment by aximov** [comment]
そういうことだったんですね、むしろありがとうございます！！

なるほど、https とか twitter.com とかをURLが含むかどうかは validation していたのですが、そういった形の入力は想定していませんでした。もう少し真面目にバリデーションとテストを書きます笑

**Comment by aximov** [comment]
まずロールバックしたのを元に戻した上で、

```sh
$ heroku pg:reset DATABASE
$ heroku run rake db:migrate
```

でDBを飛ばすと復帰した。

改めて `https://twitter.com` を登録してみると同じ状態になったので、再現できた。

@7ma7X さんありがとうございます！
